### ISSUE TITLE
TODO (ru)

### ISSUE THREAD

**Issue by Dolaxom** [Dolaxom/CPP_Messenger#1]
- [x] Авторизация
- [x] Регистрация
- [x] Инфа о пользователе
- [x] Отправка писем
- [ ] Довести MVC до ума и убрать мусор
- [ ] Ввести Conan в проект
- [x] Полностью переехать на Google Style
- [x] Баг от 245e07b коммита
- [x] История сообщений
